openapi: "3.1.0"
info:
  version: "1.0.0"
  title: "Manage tasks controller"
tags:
  - name: Tasks
    description: Manage tasks controller

paths:
  /tasks/create:
    post:
      summary: New task create
      tags:
        - Tasks
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TaskCreate"
      responses:
        '201':
          description: Task created successfully.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TaskResponse"

  /tasks/update/{id}:
    patch:
      summary: Change task status.
      tags:
        - Tasks
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The task id.
      responses:
        '200':
          description: Status of the task changed.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TaskResponse"

  /tasks/fullChange/{id}:
    put:
      summary: New task create
      tags:
        - Tasks
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The task id.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TaskCreate"
      responses:
        '200':
          description: The task was updated with the defined changes.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TaskResponse"

components:
  schemas:    
    TaskCreate:
      type: object
      properties:
        title:
          type: string
          example: teste title
          minLength: 1
          maxLength: 30
        content:
          type: string
          example: task content
          minLength: 5
          maxLength: 250
        date:
          type: string
          format: date       
          pattern: ^(20[2-9][0-9]|2100)-((0[1-9])|(1[0-2]))-(([0-2][1-9])|10|20|30|31)$   
          example: 09/17/2023
          minimum: "02-21-2023"
          description: The date should be in the format "MM-DD-YYYY" and not earlier than the current year.
        done:
          type: boolean
          default: false
          example: true

    # Schema to responde of create or find task.
    TaskResponse:
      type: object
      properties:
        id:
          type: string
          format: objectId
          example: 649cbbd89d3260b449ddb5e9
        title:
          type: string
          example: teste title
        content:
          type: string
          example: task content
        date:
          type: object
          properties:
            month:
              type: integer
              example: 9
            day:
              type: integer
              example: 17
            year:
              type: integer
              example: 2023
        done:
          type: boolean
          example: false
        createdAt:
          type: string
          format: date-time
          example: 2023-06-28T23:01:00.000Z
        userId:
          type: string
          format: uuid
          example: 649cbbc39d3260b449ddb5e6

