version: '3.7'
services:
  prisma-studio:
    build: 
      context: ./
      dockerfile: Dockerfile
    container_name: task-list
    image: tasklist:2.1.0
    restart: unless-stopped
    ports:
      - 3333:3333
    
