openapi: "3.1.0"
info:
  version: "1.0.0"
  title: "Delete tasks controller"
tags:
  - name: DeleteTasks
    description: Delete tasks controller

paths:
  /tasks/unique/{id}:
    delete:
      summary: Delete task by id
      tags:
        - DeleteTasks
    parameters:
      - in: path
        name: id
        schema:
          type: string
          format: objectId
        required: true
        description: The ID of the task you want to delete.
    responses:
      201:
        description: Created (200 Delete and 201 Created the same tasks in the trash database)
        content:
          application/json:
            schema:
              type: object
              items:
                $ref: "./schemas/task.schema.yml/#/components/schemas/TaskResponse"
    x-handler: deleteTask
    x-middleware:
      - RateLimiter(manyRequest).getMiddleware()
      - ClassMiddleware(AuthMiddleware)
    x-middleware-description:
      - |
        This route applies a rate limiter middleware to control the number of requests allowed in a certain period of time.
        It allows a maximum of 30 requests per hour.
      - |
        This route applies an authentication middleware to control the access to the route.
        It allows access only to authenticated user.
    x-controller: delete-task-controller.ts

  /tasks/all:
    delete:
      summary: Delete all task.
      tags:
        - deletedAllTasks    
    responses:
      201:
        description: Created (200 Ok (Deleted) and 201 Created are the same tasks in the trash database)   
        content: 
          - No body return.  
    x-handler: deleteTask
    x-middleware:
      - RateLimiter(fewRequest).getMiddleware()
      - ClassMiddleware(AuthMiddleware)
    x-middleware-description:
      - |
        This route applies a rate limiter middleware to control the number of requests allowed in a certain period of time.
        It allows a maximum of 30 requests per hour.
      - |
        This route applies an authentication middleware to control the access to the route.
        It allows access only to authenticated user.
    x-controller: delete-task-controller.ts
